### ISSUE TITLE
can't mkdir and cant find the outDebug path

### ISSUE THREAD

**Issue by rfhits** [franneck94/Vscode-C-Cpp-Runner#15]
whiling "build" the task, it can't create the build/Debug dir, after creating the dir manually, it can work.

then I try to "run" the .exe file, it report an error: 

`/usr/bin/sh: ./buildDebug/outDebug: No such file or directory`

I think it might be the "/" and "\\" problem, and now I have no idea about how to fix it.😭

https://user-images.githubusercontent.com/70683664/126898062-fc2f773d-db00-4f74-aee1-ed51273ba55f.mp4

**Comment by franneck94** [comment]
Hi, this seems to be related with Mingw64.
I will change the code such that the folder is created/deleted by the Extension and not by the Makefile.

**Comment by franneck94** [comment]
Should be fixed with 1.1.1

**Comment by rfhits** [comment]
the "build" task can be executed correctly, but the "run" still can't work.

I try several terminals, but all failed. 

it seems like the path error.

the video below showed the error.

https://user-images.githubusercontent.com/70683664/126957218-6f4d695a-905e-4bf4-9ec6-2ad5cf34e28d.mp4

**Comment by franneck94** [comment]
Do you have cygwin installed besides Mingw64?

**Comment by rfhits** [comment]
sorry, I dont.

**Comment by franneck94** [comment]
> the "build" task can be executed correctly, but the "run" still can't work.
> 
> I try several terminals, but all failed.
> 
> it seems like the path error.
> 
> the video below showed the error.
> 
>  20210726_160951.1.mp4

I think the problem is that the extension wants to execute outDebug but on Windows its called outDebug.exe.
Since Mingw does not work like cygwin (and unix terminals) this cant be executed.
I will look into it. Thats why i highly recommend to use cygwin instead of Mingw.

**Comment by rfhits** [comment]
ok, I will install cygwin and try it again.

**Comment by rfhits** [comment]
OK, now it work tho I still miss mingw somehow.

**Comment by franneck94** [comment]
Will be fixed today in 1.1.2

**Comment by franneck94** [comment]
Problem should be fixed now.
